version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "6080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
